// Auto-generated by cmd/tsgen/main.go. DO NOT EDIT.
// Mechanically synchronized with pkg/files structs to prevent structural drift.

export interface payload {
  name: string;
  count: number;
}

export interface DiscohookJSON {
  content?: string;
  embeds?: DiscohookEmbed[];
}

export interface DiscohookEmbed {
  title?: string;
  description?: string;
  color?: number;
  author?: DiscohookAuthor;
  footer?: DiscohookFooter;
  image?: DiscohookImage;
  thumbnail?: DiscohookImage;
  fields?: DiscohookField[];
}

export interface DiscohookAuthor {
  name?: string;
  icon_url?: string;
}

export interface DiscohookFooter {
  text?: string;
  icon_url?: string;
}

export interface DiscohookImage {
  url?: string;
}

export interface DiscohookField {
  name?: string;
  value?: string;
  inline?: boolean;
}

export interface testConfigContainer {
  secret: string;
}

export interface CustomEmbedFieldConfig {
  name: string;
  value: string;
  inline?: boolean;
}

export interface CustomEmbedPostingConfig {
  channel_id: string;
  message_id: string;
  webhook_id?: string;
  webhook_token?: string;
}

export interface CustomEmbedConfig {
  key: string;
  title?: string;
  description?: string;
  color?: number;
  author_name?: string;
  author_icon_url?: string;
  footer_text?: string;
  footer_icon_url?: string;
  image_url?: string;
  thumbnail_url?: string;
  fields?: CustomEmbedFieldConfig[];
  postings?: CustomEmbedPostingConfig[];
}

export interface RolePanelEmbedFieldConfig {
  name: string;
  value: string;
  inline?: boolean;
}

export interface RolePanelButtonConfig {
  role_id: string;
  label: string;
  emoji_name?: string;
  emoji_id?: string;
  emoji_animated?: boolean;
}

export interface RolePanelPostingConfig {
  channel_id: string;
  message_id: string;
  webhook_id?: string;
  webhook_token?: string;
}

export interface RolePanelConfig {
  key: string;
  title?: string;
  description?: string;
  color?: number;
  author_name?: string;
  author_icon_url?: string;
  footer_text?: string;
  footer_icon_url?: string;
  image_url?: string;
  thumbnail_url?: string;
  fields?: RolePanelEmbedFieldConfig[];
  buttons?: RolePanelButtonConfig[];
  postings?: RolePanelPostingConfig[];
}

export interface RuntimeConfig {
  database?: DatabaseRuntimeConfig;
  bot_theme?: string;
  disable_db_cleanup?: boolean;
  disable_message_logs?: boolean;
  disable_entry_exit_logs?: boolean;
  disable_reaction_logs?: boolean;
  disable_user_logs?: boolean;
  disable_clean_log?: boolean;
  moderation_logging?: boolean;
  log_moderation_scope?: string;
  presence_watch_user_id?: string;
  presence_watch_bot?: boolean;
  message_cache_ttl_hours?: number;
  message_delete_on_log?: boolean;
  message_cache_cleanup?: boolean;
  global_max_workers?: number;
  backfill_channel_id?: string;
  backfill_start_day?: string;
  backfill_initial_date?: string;
  mimu_welcome_string?: string;
  mimu_goodbye_string?: string;
  disable_bot_role_perm_mirror?: boolean;
  bot_role_perm_mirror_actor_role_id?: string;
  webhook_embed_updates?: WebhookEmbedUpdateConfig[];
  webhook_embed_validation?: WebhookEmbedValidationConfig;
  disable_interactive_ephemeral?: boolean;
  pastebin_dev_key?: string;
  pastebin_user_name?: string;
  pastebin_user_password?: string;
}

export interface rawRuntimeConfig {
  moderation_log_mode?: string;
  webhook_embed_update?: WebhookEmbedUpdateConfig;
}

export interface DatabaseRuntimeConfig {
  driver?: string;
  database_url?: string;
  max_open_conns?: number;
  max_idle_conns?: number;
  conn_max_lifetime_secs?: number;
  conn_max_idle_time_secs?: number;
  ping_timeout_ms?: number;
}

export interface WebhookEmbedUpdateConfig {
  message_id?: string;
  webhook_url?: string;
  embed?: unknown;
}

export interface WebhookEmbedValidationConfig {
  mode?: string;
  timeout_ms?: number;
}

export interface ChannelsConfig {
  commands?: string;
  avatar_logging?: string;
  role_update?: string;
  member_join?: string;
  member_leave?: string;
  message_edit?: string;
  message_delete?: string;
  automod_action?: string;
  moderation_case?: string;
  clean_action?: string;
  entry_backfill?: string;
}

export interface rawChannelsConfig {
  verification_cleanup?: string;
}

export interface StatsChannelConfig {
  channel_id?: string;
  label?: string;
  name_template?: string;
  member_type?: string;
  role_id?: string;
}

export interface StatsConfig {
  channels?: StatsChannelConfig[];
}

export interface AutoAssignmentConfig {
  enabled?: boolean;
  target_role?: string;
  required_roles?: string[];
}

export interface RolesConfig {
  allowed?: string[];
  dashboard_read?: string[];
  dashboard_write?: string[];
  auto_assignment?: AutoAssignmentConfig;
  booster_role?: string;
  mute_role?: string;
}

export interface rawRolesConfig {
  verification_role?: string;
}

export interface EmbedUpdateTargetConfig {
  type?: string;
  message_id?: string;
  channel_id?: string;
  webhook_url?: string;
}

export interface PartnerEntryConfig {
  fandom?: string;
  name?: string;
  link?: string;
}

export interface PartnerBoardTemplateConfig {
  title?: string;
  continuation_title?: string;
  intro?: string;
  section_header_template?: string;
  section_continuation_suffix?: string;
  section_continuation_template?: string;
  line_template?: string;
  empty_state_text?: string;
  footer_template?: string;
  other_fandom_label?: string;
  color?: number;
  disable_fandom_sorting?: boolean;
  disable_partner_sorting?: boolean;
}

export interface PartnerBoardConfig {
  template?: PartnerBoardTemplateConfig;
  partners?: PartnerEntryConfig[];
  postings?: CustomEmbedPostingConfig[];
}

export interface QOTDDeckConfig {
  id?: string;
  name?: string;
  enabled?: boolean;
  channel_id?: string;
  selection_strategy?: string;
}

export interface QOTDPublishScheduleConfig {
  hour_utc?: number;
  minute_utc?: number;
}

export interface QOTDConfig {
  verified_role_id?: string;
  active_deck_id?: string;
  decks?: QOTDDeckConfig[];
  schedule?: QOTDPublishScheduleConfig;
  suppress_scheduled_publish_dates_utc?: string[];
}

export interface UserPruneConfig {
  enabled?: boolean;
}

export interface rawUserPruneConfig {
  grace_days?: number;
  scan_interval_mins?: number;
  initial_delay_secs?: number;
  kps?: number;
  max_kicks_per_run?: number;
  exempt_role_ids?: string[];
  dry_run?: boolean;
}

export interface ReactionBlockEmojiConfig {
  kind?: string;
  value?: string;
  name?: string;
  alias?: string;
  animated?: boolean;
}

export interface ReactionBlockRuleConfig {
  reactor_user_id?: string;
  target_user_id?: string;
  emojis?: ReactionBlockEmojiConfig[];
}

export interface ReactionBlockConfig {
  rules?: ReactionBlockRuleConfig[];
}

export interface TicketsCategoryConfig {
  name?: string;
  role_id?: string;
}

export interface TicketsConfig {
  enabled?: boolean;
  transcript_channel_id?: string;
  categories?: TicketsCategoryConfig[];
}

export interface GuildConfig {
  guild_id: string;
  config_version: number;
  bot_instance_tokens?: Record<string, string>;
  bot_instance_statuses?: Record<string, string>;
  feature_routing?: Record<string, string>;
  features?: FeatureToggles;
  channels?: ChannelsConfig;
  roles?: RolesConfig;
  stats?: StatsConfig;
  roles_cache_ttl?: string;
  member_cache_ttl?: string;
  guild_cache_ttl?: string;
  channel_cache_ttl?: string;
  user_prune?: UserPruneConfig;
  partner_board?: PartnerBoardConfig;
  reaction_blocks?: ReactionBlockConfig;
  qotd?: QOTDConfig;
  tickets?: TicketsConfig;
  role_panels?: RolePanelConfig[];
  custom_embeds?: CustomEmbedConfig[];
  runtime_config?: RuntimeConfig;
  log_moderation_scope?: string;
}

export interface rawGuildConfig {
  bot_instance_id?: string;
  domain_bot_instance_ids?: Record<string, string>;
}

export interface BotConfig {
  config_version: number;
  guilds?: GuildConfig[];
  features?: FeatureToggles;
  runtime_config?: RuntimeConfig;
}

export interface CustomRPCConfig {
  default_profile?: string;
  user_profiles?: Record<string, string>;
  profiles?: CustomRPCProfile[];
}

export interface CustomRPCProfile {
  name: string;
  disabled?: boolean;
  user?: string;
  application_id: string;
  type?: string;
  url?: string;
  details?: string;
  state?: string;
  party?: RPCPartyConfig;
  timestamp?: RPCTimestampConfig;
  assets?: RPCAssetsConfig;
  buttons?: RPCButtonConfig[];
  update_interval_seconds?: number;
}

export interface RPCPartyConfig {
  id?: string;
  current?: number;
  max?: number;
}

export interface RPCTimestampConfig {
  mode?: string;
  start_unix?: number;
  end_unix?: number;
  start?: string;
  end?: string;
}

export interface RPCAssetsConfig {
  large_image_key?: string;
  large_text?: string;
  small_image_key?: string;
  small_text?: string;
}

export interface RPCButtonConfig {
  label?: string;
  url?: string;
}

export interface rawQOTDDeckConfig {
  id?: string;
  name?: string;
  enabled?: boolean;
  channel_id?: string;
  forum_channel_id?: string;
  question_channel_id?: string;
  response_channel_id?: string;
  selection_strategy?: string;
}

export interface rawQOTDPublishScheduleConfig {
  hour_utc?: number;
  minute_utc?: number;
  publish_hour_utc?: number;
  publish_minute_utc?: number;
  qotd_time_hour_utc?: number;
  qotd_time_minute_utc?: number;
}

export interface rawQOTDConfig {
  verified_role_id?: string;
  active_deck_id?: string;
  decks?: QOTDDeckConfig[];
  schedule?: rawQOTDPublishScheduleConfig;
  suppress_scheduled_publish_dates_utc?: string[];
  suppress_scheduled_publish_date_utc?: string;
  enabled?: boolean;
  channel_id?: string;
  forum_channel_id?: string;
  question_channel_id?: string;
  response_channel_id?: string;
  publish_hour_utc?: number;
  publish_minute_utc?: number;
  qotd_time_hour_utc?: number;
  qotd_time_minute_utc?: number;
}

export interface FeatureServiceToggles {
  monitoring?: boolean;
  commands?: boolean;
}

export interface FeatureLoggingToggles {
  avatar_logging?: boolean;
  role_update?: boolean;
  member_join?: boolean;
  member_leave?: boolean;
  message_process?: boolean;
  message_edit?: boolean;
  message_delete?: boolean;
  reaction_metric?: boolean;
  automod_action?: boolean;
  moderation_case?: boolean;
  clean_action?: boolean;
}

export interface FeatureModerationToggles {
  ban?: boolean;
  massban?: boolean;
  kick?: boolean;
  timeout?: boolean;
  warn?: boolean;
  warnings?: boolean;
  clean?: boolean;
}

export interface FeatureMessageCacheToggles {
  cleanup_on_startup?: boolean;
  delete_on_log?: boolean;
}

export interface FeaturePresenceWatchToggles {
  bot?: boolean;
  user?: boolean;
}

export interface FeatureMaintenanceToggles {
  db_cleanup?: boolean;
}

export interface FeatureSafetyToggles {
  bot_role_perm_mirror?: boolean;
}

export interface FeatureToggles {
  services?: FeatureServiceToggles;
  logging?: FeatureLoggingToggles;
  moderation?: FeatureModerationToggles;
  message_cache?: FeatureMessageCacheToggles;
  presence_watch?: FeaturePresenceWatchToggles;
  maintenance?: FeatureMaintenanceToggles;
  safety?: FeatureSafetyToggles;
  mute_role?: boolean;
  role_panels?: boolean;
}

