// Code generated by mockery v2.53.6. DO NOT EDIT.

package automodmocks

import (
	context "context"

	automod "github.com/small-frappuccino/discordcore/pkg/automod"

	discord "github.com/diamondburned/arikawa/v3/discord"

	mock "github.com/stretchr/testify/mock"
)

// Sink is an autogenerated mock type for the Sink type
type Sink struct {
	mock.Mock
}

type Sink_Expecter struct {
	mock *mock.Mock
}

func (_m *Sink) EXPECT() *Sink_Expecter {
	return &Sink_Expecter{mock: &_m.Mock}
}

// OnAutomodBlock provides a mock function with given fields: ctx, guildID, entry
func (_m *Sink) OnAutomodBlock(ctx context.Context, guildID discord.GuildID, entry *automod.ExecutionEvent) {
	_m.Called(ctx, guildID, entry)
}

// Sink_OnAutomodBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnAutomodBlock'
type Sink_OnAutomodBlock_Call struct {
	*mock.Call
}

// OnAutomodBlock is a helper method to define mock.On call
//   - ctx context.Context
//   - guildID discord.GuildID
//   - entry *automod.ExecutionEvent
func (_e *Sink_Expecter) OnAutomodBlock(ctx interface{}, guildID interface{}, entry interface{}) *Sink_OnAutomodBlock_Call {
	return &Sink_OnAutomodBlock_Call{Call: _e.mock.On("OnAutomodBlock", ctx, guildID, entry)}
}

func (_c *Sink_OnAutomodBlock_Call) Run(run func(ctx context.Context, guildID discord.GuildID, entry *automod.ExecutionEvent)) *Sink_OnAutomodBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(discord.GuildID), args[2].(*automod.ExecutionEvent))
	})
	return _c
}

func (_c *Sink_OnAutomodBlock_Call) Return() *Sink_OnAutomodBlock_Call {
	_c.Call.Return()
	return _c
}

func (_c *Sink_OnAutomodBlock_Call) RunAndReturn(run func(context.Context, discord.GuildID, *automod.ExecutionEvent)) *Sink_OnAutomodBlock_Call {
	_c.Run(run)
	return _c
}

// NewSink creates a new instance of Sink. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSink(t interface {
	mock.TestingT
	Cleanup(func())
}) *Sink {
	mock := &Sink{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
