package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"reflect"
	"strings"
)

// mapGoTypeToTS maps Go AST expressions to TypeScript types.
func mapGoTypeToTS(expr ast.Expr) string {
	switch e := expr.(type) {
	case *ast.Ident:
		switch e.Name {
		case "string":
			return "string"
		case "int", "int32", "int64", "float32", "float64", "uint", "uint32", "uint64":
			return "number"
		case "bool":
			return "boolean"
		case "EncryptedString":
			return "string" // We handle these as strings in TS
		case "json.RawMessage", "RawMessage":
			return "unknown"
		default:
			return e.Name // Assuming it's a struct defined elsewhere in the file
		}
	case *ast.StarExpr:
		return mapGoTypeToTS(e.X)
	case *ast.ArrayType:
		return mapGoTypeToTS(e.Elt) + "[]"
	case *ast.MapType:
		keyType := mapGoTypeToTS(e.Key)
		valType := mapGoTypeToTS(e.Value)
		return fmt.Sprintf("Record<%s, %s>", keyType, valType)
	case *ast.SelectorExpr:
		if ident, ok := e.X.(*ast.Ident); ok && ident.Name == "json" && e.Sel.Name == "RawMessage" {
			return "unknown"
		}
		if ident, ok := e.X.(*ast.Ident); ok && ident.Name == "time" && e.Sel.Name == "Time" {
			return "string"
		}
		return e.Sel.Name
	default:
		return "unknown"
	}
}

func main() {
	if len(os.Args) < 3 {
		log.Fatalf("Usage: %s <input_dir> <output_file>", os.Args[0])
	}

	inputDir := os.Args[1]
	outputFile := os.Args[2]

	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, inputDir, nil, parser.ParseComments)
	if err != nil {
		log.Fatalf("Failed to parse dir %s: %v", inputDir, err)
	}

	var out bytes.Buffer
	out.WriteString("// Auto-generated by cmd/tsgen/main.go. DO NOT EDIT.\n")
	out.WriteString("// Mechanically synchronized with pkg/files structs to prevent structural drift.\n\n")

	for _, pkg := range pkgs {
		for _, file := range pkg.Files {
			ast.Inspect(file, func(n ast.Node) bool {
				typeSpec, ok := n.(*ast.TypeSpec)
				if !ok {
					return true
				}
				structType, ok := typeSpec.Type.(*ast.StructType)
				if !ok {
					return true
				}

				// Only generate TS for structs that have JSON tags on their fields
				hasJSON := false
				for _, field := range structType.Fields.List {
					if field.Tag != nil && strings.Contains(field.Tag.Value, "json:") {
						hasJSON = true
						break
					}
				}

				// If it doesn't have JSON tags, skip it, unless it's explicitly one we want.
				// But generally, config structs all have JSON tags.
				if !hasJSON {
					return true
				}

				out.WriteString(fmt.Sprintf("export interface %s {\n", typeSpec.Name.Name))

				for _, field := range structType.Fields.List {
					if len(field.Names) == 0 {
						continue // Skip embedded structs without explicit JSON names for now
					}

					name := field.Names[0].Name
					jsonTag := ""
					if field.Tag != nil {
						// Extract `json:"foo,omitempty"`
						tagVal := field.Tag.Value[1 : len(field.Tag.Value)-1] // Remove backticks
						structTag := reflect.StructTag(tagVal)
						jsonTag = structTag.Get("json")
					}

					if jsonTag == "-" || jsonTag == "" {
						continue
					}

					parts := strings.Split(jsonTag, ",")
					jsonName := parts[0]
					if jsonName == "" {
						jsonName = name
					}

					isOptional := false
					for _, p := range parts[1:] {
						if p == "omitempty" {
							isOptional = true
						}
					}
					// Also, if it's a pointer, map, or slice, it's generally optional in TS since it might be null
					if _, ok := field.Type.(*ast.StarExpr); ok {
						isOptional = true
					}
					if _, ok := field.Type.(*ast.MapType); ok {
						isOptional = true
					}
					if _, ok := field.Type.(*ast.ArrayType); ok {
						isOptional = true
					}

					tsType := mapGoTypeToTS(field.Type)

					optMarker := ""
					if isOptional {
						optMarker = "?"
					}

					out.WriteString(fmt.Sprintf("  %s%s: %s;\n", jsonName, optMarker, tsType))
				}

				out.WriteString("}\n\n")

				return true
			})
		}
	}

	err = os.MkdirAll(filepath.Dir(outputFile), 0755)
	if err != nil {
		log.Fatalf("Failed to create output directory: %v", err)
	}

	err = os.WriteFile(outputFile, out.Bytes(), 0644)
	if err != nil {
		log.Fatalf("Failed to write output file: %v", err)
	}

	log.Printf("Successfully generated TypeScript interfaces to %s", outputFile)
}
