package control

import (
	"fmt"
	"net/http"
	"strings"
)

func (s *Server) handleGuildOAuthAuthorize(w http.ResponseWriter, r *http.Request, guildID string) {
	instanceID := r.URL.Query().Get("bot_instance_id")
	if instanceID == "" {
		http.Error(w, "bot_instance_id is required", http.StatusBadRequest)
		return
	}

	cfg := s.configManager.SnapshotConfig()
	guild, ok := findGuildSettings(cfg, guildID)
	if !ok {
		http.Error(w, "guild settings not found", http.StatusNotFound)
		return
	}

	encToken, exists := guild.BotInstanceTokens[instanceID]
	if !exists {
		http.Error(w, "bot instance not found", http.StatusNotFound)
		return
	}

	token := strings.TrimSpace(string(encToken))
	if token == "" {
		http.Error(w, "bot instance token is empty", http.StatusBadRequest)
		return
	}

	profile, err := getBotProfileCached(r.Context(), guildID, instanceID, token)
	if err != nil {
		http.Error(w, "Failed to resolve bot profile", http.StatusInternalServerError)
		return
	}

	clientID := profile.ID
	if clientID == "" {
		http.Error(w, "bot profile has no ID", http.StatusInternalServerError)
		return
	}

	// Dynamic OAuth parameters generated by the backend
	permissions := 8
	redirectURL := fmt.Sprintf("https://discord.com/api/oauth2/authorize?client_id=%s&permissions=%d&scope=bot%%20applications.commands&guild_id=%s&disable_guild_select=true", clientID, permissions, guildID)

	http.Redirect(w, r, redirectURL, http.StatusFound)
}
