// Code generated by MockGen. DO NOT EDIT.
// Source: d:\Users\alice\git\discordcore\pkg\discord\commands\runtime\commands.go
//
// Generated by this command:
//
//	mockgen -source=d:\Users\alice\git\discordcore\pkg\discord\commands\runtime\commands.go -destination=d:\Users\alice\git\discordcore\pkg\discord\commands\runtime\mock_replier_test.go -package=runtime
//

// Package runtime is a generated GoMock package.
package runtime

import (
	context "context"
	reflect "reflect"

	api "github.com/diamondburned/arikawa/v3/api"
	discord "github.com/diamondburned/arikawa/v3/discord"
	gomock "go.uber.org/mock/gomock"
)

// MockInteractionReplier is a mock of InteractionReplier interface.
type MockInteractionReplier struct {
	ctrl     *gomock.Controller
	recorder *MockInteractionReplierMockRecorder
	isgomock struct{}
}

// MockInteractionReplierMockRecorder is the mock recorder for MockInteractionReplier.
type MockInteractionReplierMockRecorder struct {
	mock *MockInteractionReplier
}

// NewMockInteractionReplier creates a new mock instance.
func NewMockInteractionReplier(ctrl *gomock.Controller) *MockInteractionReplier {
	mock := &MockInteractionReplier{ctrl: ctrl}
	mock.recorder = &MockInteractionReplierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInteractionReplier) EXPECT() *MockInteractionReplierMockRecorder {
	return m.recorder
}

// EditInteractionResponse mocks base method.
func (m *MockInteractionReplier) EditInteractionResponse(ctx context.Context, appID discord.AppID, token string, data api.EditInteractionResponseData) (*discord.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditInteractionResponse", ctx, appID, token, data)
	ret0, _ := ret[0].(*discord.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditInteractionResponse indicates an expected call of EditInteractionResponse.
func (mr *MockInteractionReplierMockRecorder) EditInteractionResponse(ctx, appID, token, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditInteractionResponse", reflect.TypeOf((*MockInteractionReplier)(nil).EditInteractionResponse), ctx, appID, token, data)
}

// RespondInteraction mocks base method.
func (m *MockInteractionReplier) RespondInteraction(ctx context.Context, interactionID discord.InteractionID, token string, resp api.InteractionResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RespondInteraction", ctx, interactionID, token, resp)
	ret0, _ := ret[0].(error)
	return ret0
}

// RespondInteraction indicates an expected call of RespondInteraction.
func (mr *MockInteractionReplierMockRecorder) RespondInteraction(ctx, interactionID, token, resp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RespondInteraction", reflect.TypeOf((*MockInteractionReplier)(nil).RespondInteraction), ctx, interactionID, token, resp)
}
