package cmd

import (
	"github.com/diamondburned/arikawa/v3/api"
)

// CommandGroup standardizes the delivery of Guild & Bot-Profile isolated slash commands to the gateway registrar.
// Allocation Footprint: Negligible. Typically returns pre-allocated static slices and maps.
// Preemption Rules: None. These methods are pure accessors and must not block or perform I/O.
type CommandGroup interface {
	// Register exposes the slice of Discord Application Command blueprints generated by the vertical's internal constructor, isolated by Guild and Bot Profile.
	// Allocation Footprint: O(1) if returning a pre-allocated slice, O(N) if generating on the fly.
	// Preemption Rules: Must return immediately without blocking.
	Register(guildID string, botProfileID string) []api.CreateCommandData

	// Handle exposes the O(1) routing dictionary binding the unique command invocation string directly to its procedural execution lane, isolated by Guild and Bot Profile.
	// Allocation Footprint: O(1) if returning a pre-allocated map.
	// Preemption Rules: Must return immediately without blocking.
	Handle(guildID string, botProfileID string) map[string]CommandHandler
}
