export const appRoutes = {
  landing: "/",
  dashboard: "/dashboard",
  dashboardHome: "/dashboard/home",
  dashboardCore: "/dashboard/core",
  dashboardCoreControlPanel: "/dashboard/core/control-panel",
  dashboardCoreStats: "/dashboard/core/stats",
  dashboardCoreCommands: "/dashboard/core/commands",
  dashboardModeration: "/dashboard/moderation",
  dashboardModerationModeration: "/dashboard/moderation/moderation",
  dashboardModerationLogging: "/dashboard/moderation/logging",
  dashboardPartnerBoard: "/dashboard/partner-board",
  partnerBoardBase: "/dashboard/partner-board",
  partnerBoardEntries: "/dashboard/partner-board/entries",
  partnerBoardLayout: "/dashboard/partner-board/layout",
  partnerBoardDelivery: "/dashboard/partner-board/delivery",
  dashboardRoles: "/dashboard/roles",
  dashboardRolesAutorole: "/dashboard/roles/autorole",
  dashboardRolesLevelRoles: "/dashboard/roles/level-roles",
  controlPanel: "/dashboard/control-panel",
  commands: "/dashboard/commands",
  moderation: "/dashboard/moderation",
  logging: "/dashboard/logging",
  roles: "/dashboard/roles",
  stats: "/dashboard/stats",
} as const;

export const partnerBoardTabs = [
  { label: "Entries", path: appRoutes.partnerBoardEntries },
  { label: "Layout", path: appRoutes.partnerBoardLayout },
  { label: "Destination", path: appRoutes.partnerBoardDelivery },
] as const;
