package app

import (
	"context"

	"github.com/diamondburned/arikawa/v3/api"
	"github.com/small-frappuccino/discordcore/pkg/discord/commands/core"
	"github.com/small-frappuccino/discordcore/pkg/files"
)

// CommandGroup standardizes the delivery of Guild & Bot-Profile isolated slash commands to the gateway registrar.
// Allocation Footprint: Negligible. Typically returns pre-allocated static slices and maps.
// Preemption Rules: None. These methods are pure accessors and must not block or perform I/O.
type CommandGroup interface {
	// Commands exposes the slice of Discord Application Command blueprints generated by the vertical's internal constructor, isolated by Guild and Bot Profile.
	// Allocation Footprint: O(1) if returning a pre-allocated slice, O(N) if generating on the fly.
	// Preemption Rules: Must return immediately without blocking.
	Commands(guildID string, botProfileID string) []api.CreateCommandData

	// Handlers exposes the O(1) routing dictionary binding the unique command invocation string directly to its procedural execution lane, isolated by Guild and Bot Profile.
	// Allocation Footprint: O(1) if returning a pre-allocated map.
	// Preemption Rules: Must return immediately without blocking.
	Handlers(guildID string, botProfileID string) map[string]core.CommandHandler
}

// FeatureService defines the passive watcher triggered by state changes.
// Allocation Footprint: Minimal overhead. Goroutine spawned for Start.
// Preemption Rules: Must respect context cancellation boundaries strictly.
type FeatureService interface {
	// Start traps execution inside its spawned goroutine and yields control exclusively to errgroup.
	// It must gracefully unwind its stack the exact clock cycle ctx.Done() returns.
	// Allocation Footprint: Small stack allocation for goroutine. No sustained heap growth.
	// Preemption Rules: Blocking call. Yields completely upon context cancellation.
	Start(ctx context.Context) error

	// Stop signals the feature service to shutdown and release any held resources gracefully.
	// Allocation Footprint: Minimal. No heap allocations expected.
	// Preemption Rules: Must return immediately or block only briefly for teardown.
	Stop() error

	// OnConfigMutated is the passive Pub/Sub reactive receiver for configuration events (equivalent to WatchConfig).
	// It receives a ConfigEvent containing the GuildID and the read-only configuration snapshot.
	// The implementer must compute feature toggles (Enable/Disable) deterministically in O(1) or O(N) local memory without acquiring global write locks.
	// Allocation Footprint: O(1) or local O(N) for evaluation. Must not escape variables to the heap unnecessarily.
	// Preemption Rules: Must execute synchronously and quickly. Should preempt if context is canceled during complex evaluation.
	OnConfigMutated(ctx context.Context, event files.ConfigEvent)
}
